version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
     - "8080:8080"
     - "8081:8081"
    volumes:
     - ${PWD}/builds.js:/usr/share/nginx/html/builds/builds.js
     - ${PWD}/factory.zip:/usr/share/nginx/html/factory.zip
    environment:
    - FLASH_URL=http://localhost:8080
    - SECURE_URL=http://localhost:8081