version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
     - "8080:8080"
     - "8081:8081"
    volumes:
     - ${PWD}/image-with-license.sh:/usr/share/nginx/html/image-with-license.sh
     - ${PWD}/android-info.txt:/usr/share/nginx/html/android-info.txt
     - ${PWD}/factory.zip:/usr/share/nginx/html/factory.zip
    networks:
    - flashnet
  api:
    build: ./api
    ports:
     - "8082:8082"
    networks:
    - flashnet

networks:
  flashnet:
    ipam:
      driver: default
